version: '3'
services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db_backup/:/home
    environment:
      - POSTGRES_PASSWORD=passowrd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dvd_rental
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./code/
    ports:
      - "5000:5000"
    volumes:
      - ./code/:/app
